org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod properties
mod_version = 2.0.0
mod_id = vendingblock
mod_id_cap = VendingBlock
mod_name = Vending Block: Restocked
mod_license = GNU GPLv3.0
mod_group = com.furglitch.vendingblock
mod_author = Furglitch
mod_description = A revival of the classic Vending Block mod!
mod_homepage = https://modrinth.com/mod/vending-block-restocked
mod_sources = https://github.com/furglitch/vending-block
mod_issues = https://github.com/furglitch/vending-block/issues
mod_updates = https://raw.githubusercontent.com/Furglitch/vending-block/refs/heads/main/updates.json
enabled_platforms = fabric,neoforge

# Minecraft
minecraft_version = 1.21.1
minecraft_version_range = >=1.21 <1.21.2

# Architectury
architectury_api_version = 13.0.8
architectury_api_version_range = >=13.0.8

# Fabric
fabric_version = 0.18.4
fabric_version_range = >=0.18.4
fabric_api_version = 0.116.7+1.21.1
fabric_api_version_range = >=0.116.7+1.21.1

# NeoForge
neoforge_version = 21.1.218
neoforge_version_range=[21.1.218,)

# Mappings
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
