name: Bug Report
description: Create a report to help us fix issues
title: "[Bug]: "
labels: ['bug']
assignees: Furglitch
body:
  - type: textarea
    id: issue
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: Describe the expected behavior

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the issue
      value: '1. '
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Minecraft version
      description: Do not put 'latest', put the version number
      value: '1.X.X'
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Mod version
      description: Do not put 'latest', put the version number
      value: '1.X.X'
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please include any logs here. This field is automatically formatted into code, so you do not need to include any backticks.
      placeholder: Paste logs here
      render: shell

  - type: textarea
    id: misc
    attributes:
      label: Additional Notes
      description: Anything else you want to add?