modLoader = "javafml"
loaderVersion = "[4,)"
license = "GNU GPLv3.0"

[[mods]]
modId = "vendingblock"
version = "${version}"
displayName = "Vending Block: Restocked"
displayURL = "https://github.com/Furglitch/vending-block"
issueTrackerURL = "https://github.com/Furglitch/vending-block/issues"
updateJSONURL = "https://raw.githubusercontent.com/Furglitch/vending-block/refs/heads/1.21.1/updates.json"
#credits = ""
authors = "Furglitch"
description = "A revival of the classic Vending Block mod, allowing players set up and use custom shops!"
logoFile="pack.png"

#[[mixins]]
#config = "vendingblock.mixins.json"

[[dependencies.vendingblock]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vendingblock]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.vendingblock]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "vendingblock.mixins.json"
